/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_program_server_service_RtspService */

#ifndef _Included_com_program_server_service_RtspService
#define _Included_com_program_server_service_RtspService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_program_server_service_RtspService
 * Method:    startServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_program_server_service_RtspService_startServer
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_program_server_service_RtspService
 * Method:    stopServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_program_server_service_RtspService_stopServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
